name: fuel_saver
description: "Find the cheapest fuel stations across 13 countries."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  maplibre_gl: ^0.25.0
  geolocator: ^13.0.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  collection: ^1.19.1
  apple_maps_flutter: ^1.4.0
  flutter_svg: ^2.2.4
  shared_preferences: ^2.2.2
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.svg
