import '../models/country_config.dart';

const countries = <String, CountryConfig>{
  'US': CountryConfig(
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    centerLng: -95.7129,
    centerLat: 37.0902,
    zoom: 4,
    currency: '\$',
    unit: 'gal',
    fuelTypes: [
      FuelType(id: 'regular', label: 'Regular'),
      FuelType(id: 'midgrade', label: 'Midgrade'),
      FuelType(id: 'premium', label: 'Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'regular',
    source: 'Fuel Price API',
    sourceUrl: '',
  ),
  'CA': CountryConfig(
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    centerLng: -75.6972,
    centerLat: 45.4215,
    zoom: 4,
    currency: '\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'regular', label: 'Regular'),
      FuelType(id: 'midgrade', label: 'Mid-Grade'),
      FuelType(id: 'premium', label: 'Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'regular',
    source: 'Fuel Price API',
    sourceUrl: '',
  ),
  'FR': CountryConfig(
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    centerLng: 2.3522,
    centerLat: 46.6034,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'E10', label: 'SP95-E10'),
      FuelType(id: 'SP98', label: 'SP98'),
      FuelType(id: 'Gazole', label: 'Diesel (B7)'),
      FuelType(id: 'SP95', label: 'SP95 (E5)'),
      FuelType(id: 'E85', label: 'E85'),
      FuelType(id: 'GPLc', label: 'GPL'),
    ],
    defaultFuel: 'E10',
    source: 'data.economie.gouv.fr',
    sourceUrl:
        'https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/api/',
  ),
  'DE': CountryConfig(
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    centerLng: 10.4515,
    centerLat: 51.1657,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e5', label: 'Super E5'),
      FuelType(id: 'e10', label: 'Super E10'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'e5',
    source: 'Tankerkönig (MTS-K)',
    sourceUrl: 'https://creativecommons.tankerkoenig.de/',
  ),
  'UK': CountryConfig(
    code: 'UK',
    name: 'United Kingdom',
    flag: '🇬🇧',
    centerLng: -1.1743,
    centerLat: 52.3555,
    zoom: 6,
    currency: 'p',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'unleaded', label: 'Unleaded'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'super_unleaded', label: 'Super Unleaded'),
    ],
    defaultFuel: 'unleaded',
    source: 'GOV.UK Fuel Finder',
    sourceUrl: 'https://www.gov.uk/guidance/access-fuel-price-data',
  ),
  'ES': CountryConfig(
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    centerLng: -3.7038,
    centerLat: 40.4168,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasolina95', label: 'Gasolina 95'),
      FuelType(id: 'gasolina98', label: 'Gasolina 98'),
      FuelType(id: 'gasoleo', label: 'Gasóleo A'),
      FuelType(id: 'glp', label: 'GLP'),
    ],
    defaultFuel: 'gasolina95',
    source: 'Ministerio (geoportalgasolineras)',
    sourceUrl:
        'https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/help',
  ),
  'IT': CountryConfig(
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    centerLng: 12.5674,
    centerLat: 41.8719,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'benzina', label: 'Benzina'),
      FuelType(id: 'gasolio', label: 'Gasolio'),
      FuelType(id: 'gpl', label: 'GPL'),
      FuelType(id: 'metano', label: 'Metano'),
    ],
    defaultFuel: 'benzina',
    source: 'MIMIT Open Data',
    sourceUrl: 'https://www.mimit.gov.it/',
  ),
  'AT': CountryConfig(
    code: 'AT',
    name: 'Austria',
    flag: '🇦🇹',
    centerLng: 13.3333,
    centerLat: 47.3333,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'SUP', label: 'Super (E5)'),
      FuelType(id: 'GOE', label: 'Diesel'),
      FuelType(id: 'GAS', label: 'CNG/Erdgas'),
    ],
    defaultFuel: 'SUP',
    source: 'E-Control Spritpreisrechner',
    sourceUrl: 'https://api.e-control.at/sprit/1.0/',
  ),
  'KR': CountryConfig(
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    centerLng: 127.7669,
    centerLat: 35.9078,
    zoom: 7,
    currency: '₩',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'B027', label: 'Gasoline'),
      FuelType(id: 'B034', label: 'Premium Gasoline'),
      FuelType(id: 'D047', label: 'Diesel'),
      FuelType(id: 'K015', label: 'LPG'),
    ],
    defaultFuel: 'B027',
    source: 'Opinet (KNOC)',
    sourceUrl: 'https://www.opinet.co.kr/',
  ),
  'CL': CountryConfig(
    code: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    centerLng: -70.6693,
    centerLat: -33.4489,
    zoom: 6,
    currency: '\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasolina93', label: 'Gasolina 93'),
      FuelType(id: 'gasolina95', label: 'Gasolina 95'),
      FuelType(id: 'gasolina97', label: 'Gasolina 97'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'glp', label: 'GLP'),
    ],
    defaultFuel: 'gasolina93',
    source: 'CNE (Comisión Nacional de Energía)',
    sourceUrl: 'https://www.cne.cl/',
  ),
  'AU': CountryConfig(
    code: 'AU',
    name: 'Australia (NSW)',
    flag: '🇦🇺',
    centerLng: 151.2093,
    centerLat: -33.8688,
    zoom: 6,
    currency: 'c',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'E10', label: 'E10'),
      FuelType(id: 'U91', label: 'Unleaded 91'),
      FuelType(id: 'P95', label: 'Premium 95'),
      FuelType(id: 'P98', label: 'Premium 98'),
      FuelType(id: 'DL', label: 'Diesel'),
      FuelType(id: 'LPG', label: 'LPG'),
    ],
    defaultFuel: 'E10',
    source: 'FuelCheck NSW',
    sourceUrl: 'https://api.nsw.gov.au/',
  ),
  'MX': CountryConfig(
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    centerLng: -99.1332,
    centerLat: 19.4326,
    zoom: 6,
    currency: '\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'regular', label: 'Regular'),
      FuelType(id: 'premium', label: 'Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'regular',
    source: 'CRE (datos.gob.mx)',
    sourceUrl: 'https://datos.gob.mx/',
  ),
  'BR': CountryConfig(
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    centerLng: -47.8825,
    centerLat: -15.7942,
    zoom: 5,
    currency: 'R\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasolina', label: 'Gasolina Comum'),
      FuelType(id: 'gasolina_ad', label: 'Gasolina Aditivada'),
      FuelType(id: 'etanol', label: 'Etanol'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'gnv', label: 'GNV'),
    ],
    defaultFuel: 'gasolina',
    source: 'ANP (Agência Nacional do Petróleo)',
    sourceUrl: 'https://www.gov.br/anp/',
  ),
  'AR': CountryConfig(
    code: 'AR',
    name: 'Argentina',
    flag: '🇦🇷',
    centerLng: -58.3816,
    centerLat: -34.6037,
    zoom: 5,
    currency: '\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'nafta_super', label: 'Nafta Súper'),
      FuelType(id: 'nafta_premium', label: 'Nafta Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'diesel_premium', label: 'Diesel Premium'),
      FuelType(id: 'gnc', label: 'GNC'),
    ],
    defaultFuel: 'nafta_super',
    source: 'Secretaría de Energía',
    sourceUrl: 'https://datos.gob.ar/dataset/energia-precios-surtidor',
  ),
  'CH': CountryConfig(
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    centerLng: 8.2275,
    centerLat: 46.8182,
    zoom: 7,
    currency: 'CHF',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'E95', label: 'Benzin 95'),
      FuelType(id: 'E98', label: 'Benzin 98'),
      FuelType(id: 'Diesel', label: 'Diesel'),
    ],
    defaultFuel: 'E95',
    source: 'Comparis.ch (TCS)',
    sourceUrl: 'https://www.comparis.ch/benzin-preise',
  ),
  'IE': CountryConfig(
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    centerLat: 53.41,
    centerLng: -8.24,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'unleaded', label: 'Unleaded'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'unleaded',
    source: 'pumps.ie',
    sourceUrl: 'https://pumps.ie/',
  ),
  'HR': CountryConfig(
    code: 'HR',
    name: 'Croatia',
    flag: '🇭🇷',
    centerLat: 45.10,
    centerLng: 15.20,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'eurosuper95', label: 'Eurosuper 95'),
      FuelType(id: 'eurosuper100', label: 'Eurosuper 100'),
      FuelType(id: 'eurodizel', label: 'Eurodizel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'eurosuper95',
    source: 'MZOE-GOR',
    sourceUrl: 'https://mzoe-gor.hr/',
  ),
  'LU': CountryConfig(
    code: 'LU',
    name: 'Luxembourg',
    flag: '🇱🇺',
    centerLat: 49.82,
    centerLng: 6.13,
    zoom: 8,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'E10', label: 'E10'),
      FuelType(id: 'SP98', label: 'SP98'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'E10',
    source: 'Carbu.com',
    sourceUrl: 'https://carbu.com/',
  ),
  'PT': CountryConfig(
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    centerLat: 39.40,
    centerLng: -8.22,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasolina_95', label: 'Gasolina 95'),
      FuelType(id: 'gasoleo', label: 'Gasóleo'),
      FuelType(id: 'gasoleo_especial', label: 'Gasóleo Especial'),
      FuelType(id: 'gpl', label: 'GPL'),
    ],
    defaultFuel: 'gasolina_95',
    source: 'DGEG',
    sourceUrl: 'https://precoscombustiveis.dgeg.gov.pt/',
  ),
  'SI': CountryConfig(
    code: 'SI',
    name: 'Slovenia',
    flag: '🇸🇮',
    centerLat: 46.56,
    centerLng: 14.99,
    zoom: 8,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: '95', label: 'Bencin 95'),
      FuelType(id: 'dizel', label: 'Dizel'),
      FuelType(id: '98', label: 'Bencin 98'),
      FuelType(id: 'avtoplin-lpg', label: 'LPG'),
    ],
    defaultFuel: '95',
    source: 'goriva.si',
    sourceUrl: 'https://goriva.si/',
  ),
  'DK': CountryConfig(
    code: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    centerLat: 56.26,
    centerLng: 9.50,
    zoom: 6,
    currency: 'kr',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e10', label: 'E10'),
      FuelType(id: 'e5', label: 'Blyfri 95'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'diesel_extra', label: 'Diesel Extra'),
    ],
    defaultFuel: 'e10',
    source: 'Q8',
    sourceUrl: 'https://beta.q8.dk/',
  ),
  'NZ': CountryConfig(
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    centerLat: -40.90,
    centerLng: 174.89,
    zoom: 5,
    currency: 'NZ\$',
    unit: 'L',
    fuelTypes: [
      FuelType(id: '91', label: '91 Unleaded'),
      FuelType(id: '95', label: '95 Premium'),
      FuelType(id: '98', label: '98 Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: '91',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  ),
  'NL': CountryConfig(
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    centerLat: 52.13,
    centerLng: 5.29,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'euro95', label: 'Euro 95'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'euro95',
    source: 'brandstof-zoeker.nl',
    sourceUrl: 'https://www.brandstof-zoeker.nl/',
  ),
  'BE': CountryConfig(
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    centerLat: 50.50,
    centerLng: 4.48,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'E10', label: 'E10'),
      FuelType(id: 'SP98', label: 'SP98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'LPG', label: 'LPG'),
    ],
    defaultFuel: 'E10',
    source: 'Carbu.com',
    sourceUrl: 'https://carbu.com/',
  ),
  'GR': CountryConfig(
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    centerLat: 39.07,
    centerLng: 21.82,
    zoom: 6,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'unleaded_95', label: 'Unleaded 95'),
      FuelType(id: 'unleaded_100', label: 'Unleaded 100'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'unleaded_95',
    source: 'fuelprices.gr',
    sourceUrl: 'https://www.fuelprices.gr/',
  ),
  'MY': CountryConfig(
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    centerLat: 4.21,
    centerLng: 101.69,
    zoom: 6,
    currency: 'RM',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'RON95', label: 'RON 95'),
      FuelType(id: 'RON97', label: 'RON 97'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'RON95',
    source: 'data.gov.my',
    sourceUrl: 'https://api.data.gov.my/',
  ),
  'AE': CountryConfig(
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    centerLat: 24.45,
    centerLng: 54.37,
    zoom: 6,
    currency: 'AED',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'super98', label: 'Super 98'),
      FuelType(id: 'special95', label: 'Special 95'),
      FuelType(id: 'eplus91', label: 'E-Plus 91'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'super98',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  ),
  'ZA': CountryConfig(
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    centerLat: -30.56,
    centerLng: 22.94,
    zoom: 5,
    currency: 'R',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'ULP95', label: 'ULP 95'),
      FuelType(id: 'ULP93', label: 'ULP 93'),
      FuelType(id: 'diesel_50', label: 'Diesel 50ppm'),
      FuelType(id: 'diesel_500', label: 'Diesel 500ppm'),
    ],
    defaultFuel: 'ULP95',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  ),
  'IN': CountryConfig(
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    centerLat: 20.59,
    centerLng: 78.96,
    zoom: 4,
    currency: '₹',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'petrol', label: 'Petrol'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'cng', label: 'CNG'),
    ],
    defaultFuel: 'petrol',
    source: 'OpenStreetMap',
    sourceUrl: 'https://www.openstreetmap.org/',
  ),
  'EE': CountryConfig(
    code: 'EE',
    name: 'Estonia',
    flag: '🇪🇪',
    centerLat: 58.60,
    centerLng: 25.01,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e95', label: 'E95'),
      FuelType(id: 'e98', label: 'E98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work',
    sourceUrl: 'https://api.gas.didnt.work/',
  ),
  'LV': CountryConfig(
    code: 'LV',
    name: 'Latvia',
    flag: '🇱🇻',
    centerLat: 56.88,
    centerLng: 24.60,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e95', label: 'E95'),
      FuelType(id: 'e98', label: 'E98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work',
    sourceUrl: 'https://api.gas.didnt.work/',
  ),
  'LT': CountryConfig(
    code: 'LT',
    name: 'Lithuania',
    flag: '🇱🇹',
    centerLat: 54.90,
    centerLng: 23.88,
    zoom: 7,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e95', label: 'E95'),
      FuelType(id: 'e98', label: 'E98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'e95',
    source: 'gas.didnt.work',
    sourceUrl: 'https://api.gas.didnt.work/',
  ),
  'PL': CountryConfig(
    code: 'PL',
    name: 'Poland',
    flag: '🇵🇱',
    centerLat: 51.92,
    centerLng: 19.14,
    zoom: 6,
    currency: 'zł',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'pb95', label: 'PB 95'),
      FuelType(id: 'pb98', label: 'PB 98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
      FuelType(id: 'on_plus', label: 'ON+'),
    ],
    defaultFuel: 'pb95',
    source: 'gas.didnt.work',
    sourceUrl: 'https://api.gas.didnt.work/',
  ),
  'TH': CountryConfig(
    code: 'TH',
    name: 'Thailand',
    flag: '🇹🇭',
    centerLat: 15.87,
    centerLng: 100.99,
    zoom: 5,
    currency: '฿',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasohol95', label: 'Gasohol 95'),
      FuelType(id: 'gasohol91', label: 'Gasohol 91'),
      FuelType(id: 'e20', label: 'E20'),
      FuelType(id: 'diesel_premium', label: 'Diesel Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'gasohol95',
    source: 'PTT / Bangchak',
    sourceUrl: 'https://orapiweb.pttor.com/',
  ),
  'JP': CountryConfig(
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    centerLat: 36.20,
    centerLng: 138.25,
    zoom: 5,
    currency: '¥',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'regular', label: 'Regular'),
      FuelType(id: 'premium', label: 'Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'regular',
    source: 'gogo.gs',
    sourceUrl: 'https://gogo.gs/',
  ),
  'ID': CountryConfig(
    code: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    centerLat: -0.79,
    centerLng: 113.92,
    zoom: 5,
    currency: 'Rp',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'pertalite', label: 'Pertalite'),
      FuelType(id: 'pertamax', label: 'Pertamax'),
      FuelType(id: 'pertamax_turbo', label: 'Pertamax Turbo'),
      FuelType(id: 'solar', label: 'Solar'),
      FuelType(id: 'dexlite', label: 'Dexlite'),
    ],
    defaultFuel: 'pertalite',
    source: 'MyPertamina',
    sourceUrl: 'https://mypertamina.id/',
  ),
  'FI': CountryConfig(
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    centerLat: 61.92,
    centerLng: 25.75,
    zoom: 5,
    currency: '€',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e95', label: 'E95'),
      FuelType(id: 'e98', label: 'E98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'e95',
    source: 'polttoaine.net',
    sourceUrl: 'https://polttoaine.net/',
  ),
  'RO': CountryConfig(
    code: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    centerLat: 45.94,
    centerLng: 24.97,
    zoom: 6,
    currency: 'lei',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'benzina95', label: 'Benzină 95'),
      FuelType(id: 'benzina_premium', label: 'Benzină Premium'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'diesel_premium', label: 'Diesel Premium'),
      FuelType(id: 'gpl', label: 'GPL'),
    ],
    defaultFuel: 'benzina95',
    source: 'PretCarburant.ro',
    sourceUrl: 'https://pretcarburant.ro/',
  ),
  'HU': CountryConfig(
    code: 'HU',
    name: 'Hungary',
    flag: '🇭🇺',
    centerLat: 47.16,
    centerLng: 19.50,
    zoom: 6,
    currency: 'Ft',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'e5', label: 'Benzin 95'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'e5',
    source: 'benzinkutarak.hu',
    sourceUrl: 'https://www.benzinkutarak.hu/',
  ),
  'CZ': CountryConfig(
    code: 'CZ',
    name: 'Czech Republic',
    flag: '🇨🇿',
    centerLat: 49.82,
    centerLng: 15.47,
    zoom: 6,
    currency: 'Kč',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'natural95', label: 'Natural 95'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'natural95',
    source: 'ceskybenzin.cz',
    sourceUrl: 'https://www.ceskybenzin.cz/',
  ),
  'NO': CountryConfig(
    code: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    centerLat: 60.47,
    centerLng: 8.47,
    zoom: 5,
    currency: 'kr',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'gasoline_95', label: 'Bensin 95'),
      FuelType(id: 'diesel', label: 'Diesel'),
    ],
    defaultFuel: 'gasoline_95',
    source: 'Drivstoffappen',
    sourceUrl: 'https://backend.drivstoffapp.no/',
  ),
  'SE': CountryConfig(
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    centerLat: 60.13,
    centerLng: 18.64,
    zoom: 5,
    currency: 'kr',
    unit: 'L',
    fuelTypes: [
      FuelType(id: '95', label: 'Bensin 95'),
      FuelType(id: '98', label: 'Bensin 98'),
      FuelType(id: 'diesel', label: 'Diesel'),
      FuelType(id: 'etanol', label: 'E85'),
    ],
    defaultFuel: '95',
    source: 'henrikhjelm.se',
    sourceUrl: 'https://henrikhjelm.se/',
  ),
  'TR': CountryConfig(
    code: 'TR',
    name: 'Turkey',
    flag: '🇹🇷',
    centerLat: 38.96,
    centerLng: 35.24,
    zoom: 5,
    currency: '₺',
    unit: 'L',
    fuelTypes: [
      FuelType(id: 'benzin95', label: 'Benzin 95'),
      FuelType(id: 'motorin', label: 'Motorin'),
      FuelType(id: 'lpg', label: 'LPG'),
    ],
    defaultFuel: 'benzin95',
    source: 'OPET',
    sourceUrl: 'https://api.opet.com.tr/',
  ),
};

const defaultCountry = 'FR';
